let greeting = 'hello';
let company = 'owu';
let domain = 'com';
let country = 'ua';
let numberOne = 1;
let numberTen = 10;
let negativeNumber = -999;
let positiveNumber = 123;
let pi = 3.14;
let eulerNumber = 2.7;
let age = 16;
let isTrue = true;
let isFalse = false;

console.log(greeting);
console.log(company);
console.log(domain);
console.log(country);
console.log(numberOne);
console.log(numberTen);
console.log(negativeNumber);
console.log(positiveNumber);
console.log(pi);
console.log(eulerNumber);
console.log(age);
console.log(isTrue);
console.log(isFalse);